# -*- coding: utf-8 -*-
"""FineTunning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10hldBHN0QMmqW3vu6T850XXarGnH6ovG
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
from torch.optim import AdamW
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset, random_split
from transformers import BertTokenizerFast, BertModel, get_scheduler
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, f1_score, precision_score, recall_score, accuracy_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import nltk
nltk.download('punkt')

# ---------------------------
# 1. Cargar datos
# ---------------------------
df = pd.read_json("/content/drive/MyDrive/Titulacion/DatasetsFinales/df_train2_featselect2.jsonl", lines=True)
#df= df.head(30)
X = df.drop('label', axis=1)
y = df['label']

# ---------------------------
# 2. Preprocesamiento de características
# ---------------------------
# TF-IDF
vectorizer = TfidfVectorizer(max_features=3000, ngram_range=(1, 2))
X_tfidf = vectorizer.fit_transform(X['transcription_processed']).toarray()
X_tfidf_df = pd.DataFrame(X_tfidf)

# Características adicionales
X_features = X.iloc[:, 3:]
X_features = X_features.fillna(X_features.mean())

# Unir TF-IDF + Características
combined_df = pd.concat([X_tfidf_df, X_features], axis=1)

combined_df.columns = combined_df.columns.astype(str)
scaler = MinMaxScaler()
normalized_df = scaler.fit_transform(combined_df)
normalized_tensor = torch.tensor(normalized_df, dtype=torch.float32)
labels_tensor = torch.tensor(y.values, dtype=torch.long)

# ---------------------------
# 3. Tokenización con BERT
# ---------------------------
model_name = "bert-base-multilingual-cased"
tokenizer = BertTokenizerFast.from_pretrained(model_name)
max_length = 64

encodings = tokenizer(X['transcription_processed'].tolist(),
                      padding=True, truncation=True,
                      max_length=max_length, return_tensors="pt")

# Dataset final
dataset = TensorDataset(encodings['input_ids'], encodings['attention_mask'], normalized_tensor, labels_tensor)

# ---------------------------
# 4. Dividir en entrenamiento y validación
# ---------------------------
train_size = int(0.8 * len(dataset))
train_dataset, val_dataset = random_split(dataset, [train_size, len(dataset) - train_size])
train_dataloader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=16)

# ---------------------------
# 5. Definir Modelo
# ---------------------------
class BertClassifier(nn.Module):
    def __init__(self, bert_model, num_extra_features):
        super().__init__()
        self.bert = bert_model
        self.dropout = nn.Dropout(0.3)
        self.fc1 = nn.Linear(bert_model.config.hidden_size + num_extra_features, 256)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(256, 2)
        self.softmax = nn.LogSoftmax(dim=1)

    def forward(self, input_ids, attention_mask, extra_features):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = outputs.pooler_output
        x = torch.cat((cls_output, extra_features), dim=1)
        x = self.dropout(self.relu(self.fc1(x)))
        return self.softmax(self.fc2(x))
# ---------------------------
# 6. Entrenamiento con Early Stopping (Basado en pérdida de validación)
# ---------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
bert = BertModel.from_pretrained(model_name)
model = BertClassifier(bert, normalized_tensor.shape[1]).to(device)

optimizer = AdamW(model.parameters(), lr=2e-5)

# Número máximo de épocas (suficientemente alto para permitir Early Stopping)
max_epochs = 100

# Parámetros de Early Stopping
patience = 3  # Número de épocas sin mejora (disminución de la pérdida de validación) antes de detener

scheduler = get_scheduler("linear", optimizer=optimizer, num_warmup_steps=0, num_training_steps=len(train_dataloader) * max_epochs)

# Calcular pesos de clases
train_labels = [label.item() for _, _, _, label in train_dataset]
class_weights = compute_class_weight('balanced', classes=np.unique(train_labels), y=train_labels)
weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)
loss_fn = nn.NLLLoss(weight=weights_tensor)

def train_epoch():
    model.train()
    total_loss = 0
    for batch in tqdm(train_dataloader):
        input_ids, attention_mask, features, labels = [b.to(device) for b in batch]
        optimizer.zero_grad()
        outputs = model(input_ids, attention_mask, features)
        loss = loss_fn(outputs, labels)
        loss.backward()
        optimizer.step()
        scheduler.step()
        total_loss += loss.item()
    return total_loss / len(train_dataloader)

def evaluate():
    model.eval()
    all_preds, all_labels = [], []
    total_loss = 0
    with torch.no_grad():
        for batch in val_dataloader:
            input_ids, attention_mask, features, labels = [b.to(device) for b in batch]
            outputs = model(input_ids, attention_mask, features)
            loss = loss_fn(outputs, labels)
            total_loss += loss.item()
            preds = torch.argmax(outputs, axis=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    val_loss = total_loss / len(val_dataloader)

    # Calculate metrics (Mantener estas métricas es útil para monitorear el rendimiento)
    macro_f1 = f1_score(all_labels, all_preds, average='macro')
    precision = precision_score(all_labels, all_preds, average='macro')
    recall = recall_score(all_labels, all_preds, average='macro')
    accuracy = accuracy_score(all_labels, all_preds)

    # Devolver la pérdida de validación y las métricas
    return val_loss, macro_f1, precision, recall, accuracy

# ---------------------------
# 7. Ejecutar entrenamiento con Early Stopping (Basado en pérdida de validación)
# ---------------------------
best_val_loss = float('inf') # Inicializar con infinito positivo para buscar el mínimo
epochs_without_improvement = 0
metrics_history = [] # Para almacenar las métricas de cada época

for epoch in range(max_epochs):
    print(f"\nEpoch {epoch + 1}/{max_epochs}")
    train_loss = train_epoch()
    print(f"Train Loss: {train_loss:.4f}")

    # Obtener la pérdida de validación y las métricas
    val_loss, macro_f1, precision, recall, accuracy = evaluate()
    print(f"Validation Loss: {val_loss:.4f}")
    print(f"Macro F1: {macro_f1:.4f}")
    #print(f"Precision: {precision:.4f}")
    #print(f"Recall: {recall:.4f}")
    #print(f"Accuracy: {accuracy:.4f}")


    # Almacenar las métricas para esta época
    metrics_history.append({
        'Epoch': epoch + 1,
        'Train Loss': train_loss,
        'Validation Loss': val_loss,
        'Macro F1': macro_f1,
        'Precision': precision,
        'Recall': recall,
        'Accuracy': accuracy
    })

    # Lógica de Early Stopping basada en la pérdida de validación
    if val_loss < best_val_loss: # Si la pérdida de validación mejora (disminuye)
        best_val_loss = val_loss
        epochs_without_improvement = 0
        # Opcional: Guardar el mejor modelo (basado en la menor pérdida de validación)
        torch.save(model.state_dict(), 'best_model_loss.pt') # Nombre de archivo diferente para distinguirlo
    else: # Si la pérdida de validación no mejora
        epochs_without_improvement += 1
        if epochs_without_improvement >= patience:
            print(f"Early stopping después de {patience} épocas sin mejora en la pérdida de validación.")
            break # Detiene el entrenamiento

# Mostrar la tabla de métricas al final
print("\nMétricas por Época:")
metrics_df = pd.DataFrame(metrics_history)
display(metrics_df)



best_epoch_metrics = metrics_df.loc[metrics_df['Macro F1'].idxmax()]
print("\nResultados de la mejor época:")
display(best_epoch_metrics)

# ---------------------------
# 8. Visualizar pérdidas
# ---------------------------
plt.figure(figsize=(10, 6))
plt.plot(metrics_df['Epoch'], metrics_df['Train Loss'], label='Pérdida de Entrenamiento')
plt.plot(metrics_df['Epoch'], metrics_df['Validation Loss'], label='Pérdida de Validación')
plt.title('Pérdida de Entrenamiento y Validación por Época')
plt.xlabel('Época')
plt.ylabel('Pérdida')
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# ---------------------------
# 9. Obtener predicciones del mejor modelo en el conjunto de validación
# ---------------------------
model.eval() # Poner el modelo en modo evaluación
all_preds, all_labels = [], []
with torch.no_grad():
    for batch in val_dataloader:
        input_ids, attention_mask, features, labels = [b.to(device) for b in batch]
        outputs = model(input_ids, attention_mask, features)
        preds = torch.argmax(outputs, axis=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# ---------------------------
# 10. Generar y graficar la matriz de confusión
# ---------------------------
cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Clase 0', 'Clase 1'], yticklabels=['Clase 0', 'Clase 1'])
plt.xlabel('Predicción')
plt.ylabel('Etiqueta Verdadera')
plt.title('Matriz de Confusión')
plt.show()